package com.example.demo.Entities;
// Generated Feb 11, 2026, 4:58:10 PM by Hibernate Tools 5.6.15.Final


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.IDENTITY;


/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,schema="dbo"
)
public class Orders  implements java.io.Serializable {


     private Integer orderId;
     private Customers customers;
     private Date orderDate;
     private String status;
     private BigDecimal totalAmount;
     private Set<Payments> paymentses = new HashSet<Payments>(0);
     private Set<OrderItems> orderItemses = new HashSet<OrderItems>(0);

    public Orders() {
    }

	
    public Orders(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Orders(Customers customers, Date orderDate, String status, BigDecimal totalAmount, Set<Payments> paymentses, Set<OrderItems> orderItemses) {
       this.customers = customers;
       this.orderDate = orderDate;
       this.status = status;
       this.totalAmount = totalAmount;
       this.paymentses = paymentses;
       this.orderItemses = orderItemses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="order_id", unique=true, nullable=false)
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id")
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    @Column(name="order_date", length=23)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="total_amount", nullable=false, precision=10)
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set<Payments> getPaymentses() {
        return this.paymentses;
    }
    
    public void setPaymentses(Set<Payments> paymentses) {
        this.paymentses = paymentses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set<OrderItems> getOrderItemses() {
        return this.orderItemses;
    }
    
    public void setOrderItemses(Set<OrderItems> orderItemses) {
        this.orderItemses = orderItemses;
    }




}


