package com.example.demo.Entities;
// Generated Feb 11, 2026, 4:58:10 PM by Hibernate Tools 5.6.15.Final


import java.math.BigDecimal;
import java.util.UUID;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * OrderItems generated by hbm2java
 */
@Entity
@Table(name="order_items"
    ,schema="dbo"
)
public class OrderItems  implements java.io.Serializable {


    private UUID orderItemId;
     private Orders orders;
     private Products products;
     private Integer productId;
     private int quantity;
     private BigDecimal price;

    public OrderItems() {
    }

	
    public OrderItems(int quantity, BigDecimal price) {
        this.quantity = quantity;
        this.price = price;
    }
    public OrderItems(Orders orders, Products products, int quantity, BigDecimal price) {
       this.orders = orders;
       this.products = products;
       this.quantity = quantity;
       this.price = price;
    }
   
     @Id @GeneratedValue(strategy=jakarta.persistence.GenerationType.UUID)

    
    @Column(name="order_item_id", unique=true, nullable=false)
    public UUID getOrderItemId() {
        return this.orderItemId;
    }
    
    public void setOrderItemId(UUID orderItemId) {
        this.orderItemId = orderItemId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id")
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", insertable=false, updatable=false)
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

    @Column(name="product_id")
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", nullable=false, precision=10)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }




}


