package com.example.demo.Entities;
// Generated Feb 11, 2026, 4:58:10 PM by Hibernate Tools 5.6.15.Final


import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Payments generated by hbm2java
 */
@Entity
@Table(name="payments"
    ,schema="dbo"
)
public class Payments  implements java.io.Serializable {


     private Integer paymentId;
     private Orders orders;
     private Date paymentDate;
     private String paymentMethod;
     private BigDecimal amount;

    public Payments() {
    }

	
    public Payments(BigDecimal amount) {
        this.amount = amount;
    }
    public Payments(Orders orders, Date paymentDate, String paymentMethod, BigDecimal amount) {
       this.orders = orders;
       this.paymentDate = paymentDate;
       this.paymentMethod = paymentMethod;
       this.amount = amount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="payment_id", unique=true, nullable=false)
    public Integer getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id")
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    @Column(name="payment_date", length=23)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    @Column(name="payment_method", length=50)
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    
    @Column(name="amount", nullable=false, precision=10)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }




}


