package com.example.demo.Entities;
// Generated Feb 11, 2026, 4:58:10 PM by Hibernate Tools 5.6.15.Final


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,schema="dbo"
)
public class Products  implements java.io.Serializable {


     private Integer productId;
     private String productName;
     private String description;
     private BigDecimal price;
     private int stockQuantity;
     private Set<OrderItems> orderItemses = new HashSet<OrderItems>(0);

    public Products() {
    }

	
    public Products(String productName, BigDecimal price, int stockQuantity) {
        this.productName = productName;
        this.price = price;
        this.stockQuantity = stockQuantity;
    }
    public Products(String productName, String description, BigDecimal price, int stockQuantity, Set<OrderItems> orderItemses) {
       this.productName = productName;
       this.description = description;
       this.price = price;
       this.stockQuantity = stockQuantity;
       this.orderItemses = orderItemses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="product_id", unique=true, nullable=false)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    
    @Column(name="product_name", nullable=false, length=100)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", nullable=false, precision=10)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="stock_quantity", nullable=false)
    public int getStockQuantity() {
        return this.stockQuantity;
    }
    
    public void setStockQuantity(int stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<OrderItems> getOrderItemses() {
        return this.orderItemses;
    }
    
    public void setOrderItemses(Set<OrderItems> orderItemses) {
        this.orderItemses = orderItemses;
    }




}


