package com.example.demo.Entities;
// Generated Feb 11, 2026, 4:58:10 PM by Hibernate Tools 5.6.15.Final


import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.Data;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,schema="dbo"
    , uniqueConstraints = @UniqueConstraint(columnNames="userId") 
)
@Data
public class Users  implements java.io.Serializable {


     private Integer primaryId;
     private Customers customers;
     private String userId;
     private String fullName;
     private Date lastLogin;
     private char enabled;

    public Users() {
    }

	
    public Users(String userId, String fullName, char enabled) {
        this.userId = userId;
        this.fullName = fullName;
        this.enabled = enabled;
    }
    public Users(Customers customers, String userId, String fullName, Date lastLogin, char enabled) {
       this.customers = customers;
       this.userId = userId;
       this.fullName = fullName;
       this.lastLogin = lastLogin;
       this.enabled = enabled;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="primaryId", unique=true, nullable=false)
    public Integer getPrimaryId() {
        return this.primaryId;
    }
    
    public void setPrimaryId(Integer primaryId) {
        this.primaryId = primaryId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id")
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    
    @Column(name="userId", unique=true, nullable=false, length=50)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="fullName", nullable=false, length=100)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    @Column(name="lastLogin", length=23)
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    
    @Column(name="enabled", nullable=false, length=1)
    public char getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(char enabled) {
        this.enabled = enabled;
    }




}


